# PlatformIO pre-build script: embed the web config UI into the firmware.
#
# Inlines web/subway_catalog.js into web/index.html (at the INJECT marker),
# gzips the result, and emits include/web_page.h as a PROGMEM byte array.
# Skipped when the header is already newer than both inputs.
import gzip
import os

Import("env")  # noqa: F821 (PlatformIO construct)

PROJECT_DIR = env.subst("$PROJECT_DIR")  # noqa: F821
HTML_PATH = os.path.join(PROJECT_DIR, "web", "index.html")
CATALOG_PATH = os.path.join(PROJECT_DIR, "web", "subway_catalog.js")
SCRIPT_PATH = os.path.join(PROJECT_DIR, "tools", "build_web.py")
OUT_PATH = os.path.join(PROJECT_DIR, "include", "web_page.h")
MARKER = "<!--INJECT:subway_catalog.js-->"


def build():
    # SCons exec()s this script, so __file__ is unavailable; use the known path.
    inputs = [HTML_PATH, CATALOG_PATH, SCRIPT_PATH]
    if os.path.exists(OUT_PATH):
        out_mtime = os.path.getmtime(OUT_PATH)
        if all(os.path.getmtime(p) <= out_mtime for p in inputs):
            return

    with open(HTML_PATH, encoding="utf-8") as f:
        html = f.read()
    with open(CATALOG_PATH, encoding="utf-8") as f:
        catalog = f.read()
    if MARKER not in html:
        raise SystemExit(f"build_web: marker {MARKER} missing from index.html")
    html = html.replace(MARKER, f"<script>\n{catalog}\n</script>")

    # mtime=0 keeps the gzip output (and therefore the header) reproducible.
    blob = gzip.compress(html.encode("utf-8"), compresslevel=9, mtime=0)

    lines = []
    for i in range(0, len(blob), 16):
        chunk = ", ".join(f"0x{b:02x}" for b in blob[i : i + 16])
        lines.append(f"    {chunk},")
    body = "\n".join(lines)
    header = (
        "// Generated by tools/build_web.py from web/index.html "
        "+ web/subway_catalog.js.\n"
        "// Do not edit by hand.\n"
        "#pragma once\n\n"
        "#include <pgmspace.h>\n\n"
        f"static const size_t INDEX_HTML_GZ_LEN = {len(blob)};\n"
        "static const uint8_t INDEX_HTML_GZ[] PROGMEM = {\n"
        f"{body}\n"
        "};\n"
    )
    os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
    with open(OUT_PATH, "w", encoding="utf-8") as f:
        f.write(header)
    print(
        f"build_web: embedded web UI, {len(html)} bytes html -> "
        f"{len(blob)} bytes gzipped"
    )


build()
